hero:
  enable: true
  intro: Hi, my name is
  title: Kozenkov Daniil
  subtitle: I am a full-stack developer
  content: |
    A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly.

about:
  enable: true
  title: About me
  content: |-
    I am a full-stack developer and I love it. I specialize in modern JavaScript frameworks such as Nest and Next.

    I am currently working as a frontend developer at [Extcorp](https://www.extcorp.co/) but I am also interested in backend development.
  skills:
    enable: true
    title: Here a few technologies I’ve been working with recently
    items:
      - Node.js
      - React
      - Next.js
      - Mobx
      - Nest.js
      - TypeORM
      - Sequelize
      - MongoDB

experience:
  enable: true
  items:
    - job: Frontend Developer
      company: Extcorp
      companyUrl: https://www.extcorp.co/
      date: April 2024 - Present
      content: |
        Chrome extension development. I work with React and Chrome API.
    - job: Full-stack Developer
      company: Docdo
      companyUrl: https://www.docdo.ru/
      date: September 2023 - January 2024
      content: |
        Full-stack development.
    - job: Backend Developer
      company: Junior Job
      companyUrl: https://www.junior-job.ru/
      date: January 2023 - June 2023
      content: |
        Backend development. I work with Nest.js and TypeORM. I also have experience with MongoDB.

contact:
  enable: true
  content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
  email: work.kozenkov@gmail.com
  btnName: Mail me
